apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: ajp-namespaces
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: nexus.cicd.svc.cluster.local:5000/tomcat-signup
          ports:
            - containerPort: 8080
      nodeSelector:
        key: worker
